name: mac_ci

on: push

jobs:
 mac_ci_job:
  runs-on: macos-latest
   
  steps:
   - name: checkout source code
     uses: actions/checkout@master
     
   - name: Install Qt
     uses: jurplel/install-qt-action@v2
     with:
      version: '5.15.2'
      host: 'mac'
      target: 'desktop'
      dir: '${{ github.workspace }}/example/'
     
   - name: install and set env
     run: |
      brew install g++-10
      brew install ninja-build
      echo "CXX=g++-10" >> $env:GITHUB_ENV
      echo "CMAKE_GENERATOR=Ninja" >> $env:GITHUB_ENV
      echo $env:myenv
     
   - name: build
     run: |
      mkdir ./build
      cd ./build
      cmake ..
      ninja
      ctest -V